# Generated by Django 4.2.3 on 2023-07-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_created_date_post_dislikes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
